//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order_detail()
        {
            this.reviews = new HashSet<review>();
        }
    
        public int id { get; set; }
        public long price { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> status_rate { get; set; }
        public Nullable<int> book_id { get; set; }
        public Nullable<int> order_id { get; set; }
    
        public virtual book book { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<review> reviews { get; set; }
        public virtual order order { get; set; }
    }
}
